### ISSUE TITLE
Add link to video presentation?

### ISSUE THREAD

**Issue by jhacksworth** [czan/stateful-check#10]
I came across this talk that was given at [ClojuTRE](https://clojutre.org/2019/#kvalevag) in Sep 2019:

- [How to do Stateful Property Testing in Clojure](https://www.youtube.com/watch?v=xw8ZFU8CGdA) – Magnus Kvalevåg

The presenter begins talking about stateful-check at [this time](https://www.youtube.com/watch?v=xw8ZFU8CGdA&feature=youtu.be&t=571) in the video.

Maybe it would be worth adding a reference to in the README.org?

**Comment by czan** [comment]
Thanks for the idea! I've added a new section for "Related talks" in README.org with a link to that talk, and "Testing the Hard Stuff and Staying Sane".
