### ISSUE TITLE
Add support for clojure.test's "is" in postconditions

### ISSUE THREAD

**Issue by r0man** [czan/stateful-check#13]
Hi @czan,

first, thanks for this nice library. It is a really cool way of testing things. I saw you have this feature about using the clojure.test `is` form in post conditions in the development branch. This is something I was longing for and I was about to look into myself. Luckily you already seemed to have solved this issue. :)

What's the state of this? Is there a chance this could make it into a release?

Thanks, Roman.

**Comment by czan** [comment]
As far as I know, it's ready to release. There's no real reason why I haven't done so yet, except for laziness.

I'll put out a release within the next 24 hours.

**Comment by r0man** [comment]
Perfect, looking forward to it.

**Comment by czan** [comment]
I've now pushed a release for `0.4.3`. You should be able to pull it from Clojars.

Thanks for the nudge!

**Comment by r0man** [comment]
Thank you. I will give it a try soon.
